// AUTO-GENERATED by scripts/generate-schema.ts — do not edit by hand.
// Run `npm run generate-schema` or `app-sync` to regenerate after schema changes.

export type TableKey = "gig_platforms" | "sources" | "applications" | "materials" | "proposals_contracts";

export type ColumnType = "text" | "date" | "enum" | "int" | "url" | "path" | "fk";

export type ColumnConfig = {
  key: string;
  label: string;
  type: ColumnType;
  editable: boolean;
  required?: boolean;
  enumKey?: string;
  references?: { table: string; displayField: string };
};

export const ENUMS: Record<string, readonly string[]> = {
  "application_type": [
    "proposal",
    "application",
    "agency_submission",
    "direct_outreach"
  ],
  "contract_status": [
    "pending",
    "active",
    "completed",
    "cancelled"
  ],
  "gig_platform_status": [
    "not_started",
    "applied",
    "waiting",
    "active",
    "blocked",
    "dead"
  ],
  "job_stage": [
    "researching",
    "drafting",
    "submitted",
    "interviewing",
    "offer",
    "closed_won",
    "closed_lost",
    "archived"
  ],
  "material_status": [
    "current",
    "needs_update",
    "retired"
  ],
  "material_type": [
    "resume",
    "cover_letter",
    "profile_snapshot",
    "writing_sample",
    "portfolio",
    "other"
  ],
  "proposal_outcome": [
    "pending",
    "no_response",
    "rejected",
    "interview",
    "hired",
    "withdrawn"
  ],
  "source_status": [
    "not_started",
    "active",
    "paused",
    "dead"
  ],
  "source_type": [
    "contracting_platform",
    "job_board",
    "agency",
    "direct",
    "referral"
  ]
} as const;

export const TABLES: Record<
  TableKey,
  {
    label: string;
    statusField: string;
    cardFields: string[];
    filters: Array<{ field: string; enumKey: string }>;
    columns: ColumnConfig[];
  }
// eslint-disable-next-line @typescript-eslint/no-explicit-any
> = {
  "gig_platforms": {
    "label": "Gig Platforms",
    "statusField": "status",
    "cardFields": [
      "name",
      "next_action",
      "next_action_at"
    ],
    "filters": [
      {
        "field": "status",
        "enumKey": "gig_platform_status"
      }
    ],
    "columns": [
      {
        "key": "id",
        "label": "ID",
        "type": "int",
        "editable": false
      },
      {
        "key": "name",
        "label": "Name",
        "type": "text",
        "editable": true,
        "required": true
      },
      {
        "key": "url",
        "label": "Url",
        "type": "url",
        "editable": true
      },
      {
        "key": "status",
        "label": "Status",
        "type": "enum",
        "editable": true,
        "enumKey": "gig_platform_status"
      },
      {
        "key": "applied_at",
        "label": "Applied",
        "type": "date",
        "editable": true
      },
      {
        "key": "next_action",
        "label": "Next Action",
        "type": "text",
        "editable": true
      },
      {
        "key": "next_action_at",
        "label": "Next Action Date",
        "type": "date",
        "editable": true
      },
      {
        "key": "notes",
        "label": "Notes",
        "type": "text",
        "editable": true
      },
      {
        "key": "created_at",
        "label": "Created",
        "type": "text",
        "editable": false
      },
      {
        "key": "updated_at",
        "label": "Updated",
        "type": "text",
        "editable": false
      }
    ]
  },
  "sources": {
    "label": "Sources",
    "statusField": "status",
    "cardFields": [
      "name",
      "type",
      "current_rate",
      "next_action"
    ],
    "filters": [
      {
        "field": "type",
        "enumKey": "source_type"
      },
      {
        "field": "status",
        "enumKey": "source_status"
      }
    ],
    "columns": [
      {
        "key": "id",
        "label": "ID",
        "type": "int",
        "editable": false
      },
      {
        "key": "name",
        "label": "Name",
        "type": "text",
        "editable": true,
        "required": true
      },
      {
        "key": "type",
        "label": "Type",
        "type": "enum",
        "editable": true,
        "enumKey": "source_type",
        "required": true
      },
      {
        "key": "url",
        "label": "Url",
        "type": "url",
        "editable": true
      },
      {
        "key": "status",
        "label": "Status",
        "type": "enum",
        "editable": true,
        "enumKey": "source_status"
      },
      {
        "key": "profile_url",
        "label": "Profile URL",
        "type": "url",
        "editable": true
      },
      {
        "key": "current_rate",
        "label": "Current Rate",
        "type": "text",
        "editable": true
      },
      {
        "key": "connects_balance",
        "label": "Connects Balance",
        "type": "int",
        "editable": true
      },
      {
        "key": "connects_per_proposal",
        "label": "Connects / Proposal",
        "type": "int",
        "editable": true
      },
      {
        "key": "submission_notes",
        "label": "Submission Notes",
        "type": "text",
        "editable": true
      },
      {
        "key": "next_action",
        "label": "Next Action",
        "type": "text",
        "editable": true
      },
      {
        "key": "next_action_at",
        "label": "Next Action Date",
        "type": "date",
        "editable": true
      },
      {
        "key": "notes",
        "label": "Notes",
        "type": "text",
        "editable": true
      },
      {
        "key": "profile_files_path",
        "label": "Profile Files",
        "type": "path",
        "editable": true
      },
      {
        "key": "created_at",
        "label": "Created",
        "type": "text",
        "editable": false
      },
      {
        "key": "updated_at",
        "label": "Updated",
        "type": "text",
        "editable": false
      }
    ]
  },
  "applications": {
    "label": "Applications",
    "statusField": "stage",
    "cardFields": [
      "role_title",
      "company",
      "rate_or_salary",
      "outcome",
      "next_action_at"
    ],
    "filters": [
      {
        "field": "stage",
        "enumKey": "job_stage"
      },
      {
        "field": "type",
        "enumKey": "application_type"
      },
      {
        "field": "outcome",
        "enumKey": "proposal_outcome"
      }
    ],
    "columns": [
      {
        "key": "id",
        "label": "ID",
        "type": "int",
        "editable": false
      },
      {
        "key": "role_title",
        "label": "Role Title",
        "type": "text",
        "editable": true,
        "required": true
      },
      {
        "key": "company",
        "label": "Company",
        "type": "text",
        "editable": true,
        "required": true
      },
      {
        "key": "type",
        "label": "Type",
        "type": "enum",
        "editable": true,
        "enumKey": "application_type"
      },
      {
        "key": "source_id",
        "label": "Source",
        "type": "fk",
        "editable": true,
        "references": {
          "table": "sources",
          "displayField": "name"
        }
      },
      {
        "key": "job_posting_url",
        "label": "Posting URL",
        "type": "url",
        "editable": true
      },
      {
        "key": "stage",
        "label": "Stage",
        "type": "enum",
        "editable": true,
        "enumKey": "job_stage"
      },
      {
        "key": "rate_or_salary",
        "label": "Rate / Salary",
        "type": "text",
        "editable": true
      },
      {
        "key": "submitted_at",
        "label": "Submitted",
        "type": "date",
        "editable": true
      },
      {
        "key": "next_action",
        "label": "Next Action",
        "type": "text",
        "editable": true
      },
      {
        "key": "next_action_at",
        "label": "Next Action Date",
        "type": "date",
        "editable": true
      },
      {
        "key": "notes",
        "label": "Notes",
        "type": "text",
        "editable": true
      },
      {
        "key": "local_files_path",
        "label": "Local Files",
        "type": "path",
        "editable": true
      },
      {
        "key": "connects_spent",
        "label": "Connects Spent",
        "type": "int",
        "editable": true
      },
      {
        "key": "outcome",
        "label": "Outcome",
        "type": "enum",
        "editable": true,
        "enumKey": "proposal_outcome"
      },
      {
        "key": "created_at",
        "label": "Created",
        "type": "text",
        "editable": false
      },
      {
        "key": "updated_at",
        "label": "Updated",
        "type": "text",
        "editable": false
      }
    ]
  },
  "materials": {
    "label": "Materials",
    "statusField": "status",
    "cardFields": [
      "name",
      "type",
      "version_label",
      "status"
    ],
    "filters": [
      {
        "field": "type",
        "enumKey": "material_type"
      },
      {
        "field": "status",
        "enumKey": "material_status"
      }
    ],
    "columns": [
      {
        "key": "id",
        "label": "ID",
        "type": "int",
        "editable": false
      },
      {
        "key": "name",
        "label": "Name",
        "type": "text",
        "editable": true,
        "required": true
      },
      {
        "key": "type",
        "label": "Type",
        "type": "enum",
        "editable": true,
        "enumKey": "material_type",
        "required": true
      },
      {
        "key": "file_path",
        "label": "File Path",
        "type": "path",
        "editable": true
      },
      {
        "key": "version_label",
        "label": "Version Label",
        "type": "text",
        "editable": true
      },
      {
        "key": "status",
        "label": "Status",
        "type": "enum",
        "editable": true,
        "enumKey": "material_status"
      },
      {
        "key": "notes",
        "label": "Notes",
        "type": "text",
        "editable": true
      },
      {
        "key": "created_at",
        "label": "Created",
        "type": "text",
        "editable": false
      },
      {
        "key": "updated_at",
        "label": "Updated",
        "type": "text",
        "editable": false
      }
    ]
  },
  "proposals_contracts": {
    "label": "Contracts",
    "statusField": "status",
    "cardFields": [
      "application_id",
      "status",
      "rate",
      "start_date"
    ],
    "filters": [
      {
        "field": "status",
        "enumKey": "contract_status"
      }
    ],
    "columns": [
      {
        "key": "id",
        "label": "ID",
        "type": "int",
        "editable": false
      },
      {
        "key": "application_id",
        "label": "Application",
        "type": "fk",
        "editable": true,
        "required": true,
        "references": {
          "table": "applications",
          "displayField": "role_title"
        }
      },
      {
        "key": "status",
        "label": "Status",
        "type": "enum",
        "editable": true,
        "enumKey": "contract_status"
      },
      {
        "key": "rate",
        "label": "Rate",
        "type": "text",
        "editable": true
      },
      {
        "key": "start_date",
        "label": "Start Date",
        "type": "date",
        "editable": true
      },
      {
        "key": "end_date",
        "label": "End Date",
        "type": "date",
        "editable": true
      },
      {
        "key": "notes",
        "label": "Notes",
        "type": "text",
        "editable": true
      },
      {
        "key": "created_at",
        "label": "Created",
        "type": "text",
        "editable": false
      },
      {
        "key": "updated_at",
        "label": "Updated",
        "type": "text",
        "editable": false
      }
    ]
  }
} as any;
